const followers = [
  {
    login: "A-ElNawawy",
    id: 50282244,
    node_id: "MDQ6VXNlcjUwMjgyMjQ0",
    avatar_url: "https://avatars3.githubusercontent.com/u/50282244?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/A-ElNawawy",
    html_url: "https://github.com/A-ElNawawy",
    followers_url: "https://api.github.com/users/A-ElNawawy/followers",
    following_url:
      "https://api.github.com/users/A-ElNawawy/following{/other_user}",
    gists_url: "https://api.github.com/users/A-ElNawawy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/A-ElNawawy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/A-ElNawawy/subscriptions",
    organizations_url: "https://api.github.com/users/A-ElNawawy/orgs",
    repos_url: "https://api.github.com/users/A-ElNawawy/repos",
    events_url: "https://api.github.com/users/A-ElNawawy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/A-ElNawawy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kareemlashin",
    id: 58936937,
    node_id: "MDQ6VXNlcjU4OTM2OTM3",
    avatar_url: "https://avatars0.githubusercontent.com/u/58936937?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kareemlashin",
    html_url: "https://github.com/kareemlashin",
    followers_url: "https://api.github.com/users/kareemlashin/followers",
    following_url:
      "https://api.github.com/users/kareemlashin/following{/other_user}",
    gists_url: "https://api.github.com/users/kareemlashin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/kareemlashin/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/kareemlashin/subscriptions",
    organizations_url: "https://api.github.com/users/kareemlashin/orgs",
    repos_url: "https://api.github.com/users/kareemlashin/repos",
    events_url: "https://api.github.com/users/kareemlashin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kareemlashin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ahmedamged",
    id: 23351118,
    node_id: "MDQ6VXNlcjIzMzUxMTE4",
    avatar_url: "https://avatars0.githubusercontent.com/u/23351118?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ahmedamged",
    html_url: "https://github.com/ahmedamged",
    followers_url: "https://api.github.com/users/ahmedamged/followers",
    following_url:
      "https://api.github.com/users/ahmedamged/following{/other_user}",
    gists_url: "https://api.github.com/users/ahmedamged/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ahmedamged/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ahmedamged/subscriptions",
    organizations_url: "https://api.github.com/users/ahmedamged/orgs",
    repos_url: "https://api.github.com/users/ahmedamged/repos",
    events_url: "https://api.github.com/users/ahmedamged/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ahmedamged/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Zo3rb",
    id: 58803883,
    node_id: "MDQ6VXNlcjU4ODAzODgz",
    avatar_url: "https://avatars0.githubusercontent.com/u/58803883?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Zo3rb",
    html_url: "https://github.com/Zo3rb",
    followers_url: "https://api.github.com/users/Zo3rb/followers",
    following_url: "https://api.github.com/users/Zo3rb/following{/other_user}",
    gists_url: "https://api.github.com/users/Zo3rb/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Zo3rb/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Zo3rb/subscriptions",
    organizations_url: "https://api.github.com/users/Zo3rb/orgs",
    repos_url: "https://api.github.com/users/Zo3rb/repos",
    events_url: "https://api.github.com/users/Zo3rb/events{/privacy}",
    received_events_url: "https://api.github.com/users/Zo3rb/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MBR11",
    id: 64369351,
    node_id: "MDQ6VXNlcjY0MzY5MzUx",
    avatar_url: "https://avatars2.githubusercontent.com/u/64369351?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MBR11",
    html_url: "https://github.com/MBR11",
    followers_url: "https://api.github.com/users/MBR11/followers",
    following_url: "https://api.github.com/users/MBR11/following{/other_user}",
    gists_url: "https://api.github.com/users/MBR11/gists{/gist_id}",
    starred_url: "https://api.github.com/users/MBR11/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MBR11/subscriptions",
    organizations_url: "https://api.github.com/users/MBR11/orgs",
    repos_url: "https://api.github.com/users/MBR11/repos",
    events_url: "https://api.github.com/users/MBR11/events{/privacy}",
    received_events_url: "https://api.github.com/users/MBR11/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MoatazAbdAlmageed",
    id: 17373050,
    node_id: "MDQ6VXNlcjE3MzczMDUw",
    avatar_url: "https://avatars2.githubusercontent.com/u/17373050?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MoatazAbdAlmageed",
    html_url: "https://github.com/MoatazAbdAlmageed",
    followers_url: "https://api.github.com/users/MoatazAbdAlmageed/followers",
    following_url:
      "https://api.github.com/users/MoatazAbdAlmageed/following{/other_user}",
    gists_url: "https://api.github.com/users/MoatazAbdAlmageed/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MoatazAbdAlmageed/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MoatazAbdAlmageed/subscriptions",
    organizations_url: "https://api.github.com/users/MoatazAbdAlmageed/orgs",
    repos_url: "https://api.github.com/users/MoatazAbdAlmageed/repos",
    events_url:
      "https://api.github.com/users/MoatazAbdAlmageed/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MoatazAbdAlmageed/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ahmed-elgendy",
    id: 65793731,
    node_id: "MDQ6VXNlcjY1NzkzNzMx",
    avatar_url: "https://avatars3.githubusercontent.com/u/65793731?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ahmed-elgendy",
    html_url: "https://github.com/ahmed-elgendy",
    followers_url: "https://api.github.com/users/ahmed-elgendy/followers",
    following_url:
      "https://api.github.com/users/ahmed-elgendy/following{/other_user}",
    gists_url: "https://api.github.com/users/ahmed-elgendy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ahmed-elgendy/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ahmed-elgendy/subscriptions",
    organizations_url: "https://api.github.com/users/ahmed-elgendy/orgs",
    repos_url: "https://api.github.com/users/ahmed-elgendy/repos",
    events_url: "https://api.github.com/users/ahmed-elgendy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ahmed-elgendy/received_events",
    type: "User",
    site_admin: false,
  },
];
export default followers;
